services:
  # KRaft Controllers
  controller1:
    image: confluentinc/cp-server:${CP_VERSION}
    hostname: controller1
    container_name: controller1
    volumes:
      - data-controller1:/var/lib/kafka/data
    environment:
      # Common
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://controller1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_NODE_ID: 101
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@controller1:9093,102@controller2:9093,103@controller3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${KRAFT_CLUSTER_ID}
      KAFKA_KRAFT_REPLICATION_FACTOR: 3
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_ENABLE: true
      KAFKA_CONFLUENT_BALANCER_ENABLE: false

  controller2:
    image: confluentinc/cp-server:${CP_VERSION}
    hostname: controller2
    container_name: controller2
    volumes:
      - data-controller2:/var/lib/kafka/data
    environment:
      # Common
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://controller2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_NODE_ID: 102
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@controller1:9093,102@controller2:9093,103@controller3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${KRAFT_CLUSTER_ID}
      KAFKA_KRAFT_REPLICATION_FACTOR: 3
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_ENABLE: true
      KAFKA_CONFLUENT_BALANCER_ENABLE: false

  controller3:
    image: confluentinc/cp-server:${CP_VERSION}
    hostname: controller3
    container_name: controller3
    volumes:
      - data-controller3:/var/lib/kafka/data
    environment:
      # Common
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://controller3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_NODE_ID: 103
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@controller1:9093,102@controller2:9093,103@controller3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${KRAFT_CLUSTER_ID}
      KAFKA_KRAFT_REPLICATION_FACTOR: 3
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_ENABLE: true
      KAFKA_CONFLUENT_BALANCER_ENABLE: false

  controller4:
    image: confluentinc/cp-server:${CP_VERSION}
    hostname: controller4
    container_name: controller4
    volumes:
      - data-controller4:/var/lib/kafka/data
    profiles:
      - controllerMigration
    environment:
      # Common
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://controller4:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_NODE_ID: 104
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@controller1:9093,102@controller2:9093,104@controller4:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${KRAFT_CLUSTER_ID}
      KAFKA_KRAFT_REPLICATION_FACTOR: 3
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_ENABLE: true
      KAFKA_CONFLUENT_BALANCER_ENABLE: false

  broker1:
    image: confluentinc/cp-server:${CP_VERSION}
    hostname: broker1
    container_name: broker1
    ports:
      - "9092:29092"
    volumes:
      - data-broker1:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "nc", "-z", "broker1", "9092" ]
    environment:
      KAFKA_LISTENERS: 'PLAINTEXT://broker1:9092,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: true
      CONFLUENT_LINK_COORDINATOR_ENABLE: true
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_ENABLE: true
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@controller1:9093,102@controller2:9093,103@controller3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker
      CLUSTER_ID: ${KRAFT_CLUSTER_ID}
      KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: false
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KAFKA_CONFLUENT_BALANCER_ENABLE: false
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICA: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 12
      KAFKA_LOG_SEGMENT_BYTES: 1048576 #1Mb
      KAFKA_LOG_RETENTION_BYTES: 134217728 #128Mb
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "broker1:9092"

  broker2:
    image: confluentinc/cp-server:${CP_VERSION}
    hostname: broker2
    container_name: broker2
    ports:
      - "19093:29093"
    volumes:
      - data-broker2:/var/lib/kafka/data
      - ./kraft:/tmp/kraft
    healthcheck:
      test: [ "CMD", "nc", "-z", "broker2", "9092" ]
    environment:
      KAFKA_LISTENERS: 'PLAINTEXT://broker2:9092,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: true
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_ENABLE: true
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@controller1:9093,102@controller2:9093,103@controller3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      CLUSTER_ID: ${KRAFT_CLUSTER_ID}
      KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: false
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KAFKA_CONFLUENT_BALANCER_ENABLE: false
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICA: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 12
      KAFKA_LOG_SEGMENT_BYTES: 1048576 #1Mb
      KAFKA_LOG_RETENTION_BYTES: 134217728 #128Mb
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "broker1:9092"

  schema-registry:
    image: confluentinc/cp-schema-registry:${CP_VERSION}
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker1
      - broker2
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker1:9092,broker2:9092'
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      # TODO
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper1:21811,zookeeper2:21812,zookeeper3:21813

  control-center:
    image: confluentinc/cp-enterprise-control-center:${CP_VERSION}
    hostname: control-center
    container_name: control-center
    profiles:
      - controlcenter
    depends_on:
      - broker1
      - broker2
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker1:9092,broker2:9092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

volumes:
  data-broker1:
    driver: local
  data-broker2:
    driver: local
  data-controller1:
    driver: local
  data-controller2:
    driver: local
  data-controller3:
    driver: local
  data-controller4:
    driver: local
